<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'SoftUniBlogBundle\Form\ArticleType' shared autowired service.

return $this->services['SoftUniBlogBundle\Form\ArticleType'] = new \SoftUniBlogBundle\Form\ArticleType();
