<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'SoftUniBlogBundle\Controller\ArticleController' shared autowired service.

return $this->services['SoftUniBlogBundle\Controller\ArticleController'] = new \SoftUniBlogBundle\Controller\ArticleController();
