<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwydf1p\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwydf1p/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFwydf1p.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFwydf1p\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFwydf1p\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fwydf1p',
    'container.build_id' => 'b9e8c4f0',
    'container.build_time' => 1522864184,
));
